### ISSUE TITLE
Extension - Contained app crashes and Extension does not recover

### ISSUE THREAD

**Issue by huntharo** [pwrdrvr/lambda-dispatch#50]
## Motivations
- If the contained app refuses connections then we need to throw out of the Lambda handler
- We're going to lose some requests in this case because the contained app may crash when it already has requests sent to it

## Acceptance Criteria
- Detect the exception
- Throw an exception out of the Lambda handler so the exec env will be recreated
- Fix the error in this specific case in the demo-app

## LambaLB Logs

```log
=> LambdaId: 3170030e-384d-46ea-8353-8199743d7e04 => TaskNumber: 8 => ChannelId: 09e65c5b-c262-469d-a791-430e8cbfc552
--
Exception caught in task
System.Net.Http.HttpRequestException: Connection refused (localhost:3000)
---> System.Net.Sockets.SocketException (111): Connection refused
at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError, CancellationToken) + 0x4c
at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16) + 0x60
at System.Net.Sockets.Socket.<<ConnectAsync>g__WaitForConnectWithCancellation\|285_0>d.MoveNext() + 0x1bc
--- End of stack trace from previous location ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x24
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x100
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task, ConfigureAwaitOptions) + 0x68
at System.Net.Http.HttpConnectionPool.<ConnectToTcpHostAsync>d__104.MoveNext() + 0x714
--- End of inner exception stack trace ---
at System.Net.Http.HttpConnectionPool.<ConnectToTcpHostAsync>d__104.MoveNext() + 0x79c
--- End of stack trace from previous location ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x24
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x100
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task, ConfigureAwaitOptions) + 0x68
at System.Net.Http.HttpConnectionPool.<ConnectAsync>d__103.MoveNext() + 0x1dc
--- End of stack trace from previous location ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x24
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x100
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task, ConfigureAwaitOptions) + 0x68
at System.Net.Http.HttpConnectionPool.<CreateHttp11ConnectionAsync>d__105.MoveNext() + 0x1b8
--- End of stack trace from previous location ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x24
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x100
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task, ConfigureAwaitOptions) + 0x68
at System.Net.Http.HttpConnectionPool.<AddHttp11ConnectionAsync>d__79.MoveNext() + 0x350
--- End of stack trace from previous location ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x24
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x100
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task, ConfigureAwaitOptions) + 0x68
at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.<WaitWithCancellationAsync>d__1.MoveNext() + 0x178
--- End of stack trace from previous location ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x24
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x100
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task, ConfigureAwaitOptions) + 0x68
at System.Net.Http.HttpConnectionPool.<SendWithVersionDetectionAndRetryAsync>d__89.MoveNext() + 0xac0
--- End of stack trace from previous location ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x24
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x100
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task, ConfigureAwaitOptions) + 0x68
at System.Net.Http.RedirectHandler.<SendAsync>d__4.MoveNext() + 0x184
--- End of stack trace from previous location ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x24
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x100
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task, ConfigureAwaitOptions) + 0x68
at System.Net.Http.HttpClient.<<SendAsync>g__Core\|83_0>d.MoveNext() + 0x3d8
--- End of stack trace from previous location ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x24
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x100
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task, ConfigureAwaitOptions) + 0x68
at PwrDrvr.LambdaDispatch.LambdaLB.Function.<>c__DisplayClass9_1.<<FunctionHandler>b__1>d.MoveNext() + 0x740
01:01:25.580 warn: PwrDrvr.LambdaDispatch.LambdaLB.Function[0]
=> LambdaId: 3170030e-384d-46ea-8353-8199743d7e04 => TaskNumber: 8 => ChannelId: 09e65c5b-c262-469d-a791-430e8cbfc552
Connection refused
```

## Contained App Logs
```log
Starting task
--
/app/dist/app.cjs:476
throw new TypeError("invalid media type");
^
TypeError: invalid media type
at Object.parse2 [as parse] (/app/dist/app.cjs:476:15)
at setCharset (/app/dist/app.cjs:20086:32)
at ServerResponse.send2 [as send] (/app/dist/app.cjs:21472:36)
at ServerResponse.json (/app/dist/app.cjs:21536:19)
at ServerResponse.send2 [as send] (/app/dist/app.cjs:21464:25)
at /app/dist/app.cjs:71216:9
at Layer.handle [as handle_request] (/app/dist/app.cjs:17246:9)
at next (/app/dist/app.cjs:17415:17)
at rawParser (/app/dist/app.cjs:14424:11)
at Layer.handle [as handle_request] (/app/dist/app.cjs:17246:9)
Node.js v18.18.2
01:01:25.580 fail: PwrDrvr.LambdaDispatch.LambdaLB.Function[0]
```

**Comment by huntharo** [comment]
This should no longer be an issue because #72 starts our proxy as an extension and the app starts as pid 1 (right?) so if pid 1 exits, Lambda should stop; docker definitely will stop but that's not exactly the same.
